install.packages("lmerTest")
install.packages("tidyverse")
install.packages("emmeans")
library(lmerTest)
library(tidyverse)
library(emmeans)
si_data <- as.data.frame(read.csv("data/real_data/cleaned_si_df.csv"))
my_mod <- lmer(Si_ppm ~ Induction * Species + (1|Genotype), si_data)
summary(my_mod)
anova(my_mod)
emmeans(my_mod, list(pairwise ~ Species), adjust = "tukey", type = "response")
emmeans(my_mod, list(pairwise ~ Induction), adjust = "tukey", type = "response")
